/**
 * Contract ABIs for NodeRails smart contracts.
 *
 * Only the function / event fragments we actually use are included
 * so viem can derive fully-typed calldata helpers.
 */

export const superAdminProofComponents = [
  { name: 'nonce', type: 'uint256' },
  { name: 'deadline', type: 'uint256' },
  {
    name: 'targets',
    type: 'tuple[]',
    components: [
      { name: 'chainId', type: 'uint256' },
      { name: 'contractAddress', type: 'address' },
    ],
  },
  { name: 'signatures', type: 'bytes' },
] as const;

export const nodeRailsEscrowAbi = [
  // ── Functions ──
  {
    type: 'function',
    name: 'captureNativePayment',
    stateMutability: 'payable',
    inputs: [
      { name: 'paymentIntentId', type: 'bytes32' },
      { name: 'merchant', type: 'address' },
      { name: 'feeBps', type: 'uint16' },
      { name: 'timelocks', type: 'uint256' },
      { name: 'noderailsSignature', type: 'bytes' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'captureERC20Payment',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'paymentIntentId', type: 'bytes32' },
      { name: 'merchant', type: 'address' },
      { name: 'token', type: 'address' },
      { name: 'amount', type: 'uint256' },
      { name: 'payer', type: 'address' },
      { name: 'feeBps', type: 'uint16' },
      { name: 'timelocks', type: 'uint256' },
      {
        name: 'permitData',
        type: 'tuple',
        components: [
          { name: 'amount', type: 'uint256' },
          { name: 'deadline', type: 'uint256' },
          { name: 'v', type: 'uint8' },
          { name: 'r', type: 'bytes32' },
          { name: 's', type: 'bytes32' },
        ],
      },
      { name: 'noderailsSignature', type: 'bytes' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'settlePayment',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'paymentIntentId', type: 'bytes32' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'refundPayment',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'paymentIntentId', type: 'bytes32' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'refundPaymentAmount',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'paymentIntentId', type: 'bytes32' },
      { name: 'amt', type: 'uint256' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'settleAmount',
    stateMutability: 'view',
    inputs: [{ name: 'paymentIntentId', type: 'bytes32' }],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'initiateDispute',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'paymentIntentId', type: 'bytes32' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'resolveDispute',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'paymentIntentId', type: 'bytes32' },
      { name: 'winner', type: 'address' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'captureAndConvert',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'paymentIntentId', type: 'bytes32' },
      { name: 'merchant', type: 'address' },
      { name: 'sourceToken', type: 'address' },
      { name: 'amountIn', type: 'uint256' },
      { name: 'settlementToken', type: 'address' },
      { name: 'minAmountOut', type: 'uint256' },
      { name: 'router', type: 'address' },
      { name: 'swapCalldataHash', type: 'bytes32' },
      { name: 'feeBps', type: 'uint16' },
      { name: 'timelocks', type: 'uint256' },
      {
        name: 'permitData',
        type: 'tuple',
        components: [
          { name: 'amount', type: 'uint256' },
          { name: 'deadline', type: 'uint256' },
          { name: 'v', type: 'uint8' },
          { name: 'r', type: 'bytes32' },
          { name: 's', type: 'bytes32' },
        ],
      },
      { name: 'payer', type: 'address' },
      { name: 'swapCalldata', type: 'bytes' },
      { name: 'noderailsSignature', type: 'bytes' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'captureNativeAndConvert',
    stateMutability: 'payable',
    inputs: [
      { name: 'paymentIntentId', type: 'bytes32' },
      { name: 'merchant', type: 'address' },
      { name: 'settlementToken', type: 'address' },
      { name: 'minAmountOut', type: 'uint256' },
      { name: 'router', type: 'address' },
      { name: 'swapCalldataHash', type: 'bytes32' },
      { name: 'feeBps', type: 'uint16' },
      { name: 'timelocks', type: 'uint256' },
      { name: 'swapCalldata', type: 'bytes' },
      { name: 'noderailsSignature', type: 'bytes' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'settleToMerchantBalance',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'paymentIntentId', type: 'bytes32' },
      { name: 'token', type: 'address' },
      { name: 'settlementChainId', type: 'uint256' },
      { name: 'settlementEscrow', type: 'address' },
      { name: 'router', type: 'address' },
      { name: 'bridgeCalldataHash', type: 'bytes32' },
      { name: 'minDestinationAmount', type: 'uint256' },
      { name: 'destination', type: 'address' },
      { name: 'bridgeCalldata', type: 'bytes' },
      { name: 'noderailsSignature', type: 'bytes' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'retrySettleToMerchantBalance',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'paymentIntentId', type: 'bytes32' },
      { name: 'token', type: 'address' },
      { name: 'settlementChainId', type: 'uint256' },
      { name: 'settlementEscrow', type: 'address' },
      { name: 'router', type: 'address' },
      { name: 'bridgeCalldataHash', type: 'bytes32' },
      { name: 'minDestinationAmount', type: 'uint256' },
      { name: 'destination', type: 'address' },
      { name: 'bridgeCalldata', type: 'bytes' },
      { name: 'noderailsSignature', type: 'bytes' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'creditMerchantBalance',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'paymentIntentId', type: 'bytes32' },
      { name: 'merchant', type: 'address' },
      { name: 'token', type: 'address' },
      { name: 'minAmount', type: 'uint256' },
      { name: 'destination', type: 'address' },
      { name: 'noderailsSignature', type: 'bytes' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'settleStuckMerchantBalance',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'paymentIntentId', type: 'bytes32' },
      { name: 'merchant', type: 'address' },
      { name: 'token', type: 'address' },
      { name: 'minAmount', type: 'uint256' },
      { name: 'destination', type: 'address' },
      { name: 'noderailsSignature', type: 'bytes' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'settleToBank',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'paymentIntentId', type: 'bytes32' },
      { name: 'merchant', type: 'address' },
      { name: 'token', type: 'address' },
      { name: 'amount', type: 'uint256' },
      { name: 'depositAddress', type: 'address' },
      { name: 'bankSettlementId', type: 'bytes32' },
      { name: 'authValidUntil', type: 'uint256' },
      { name: 'merchantSignature', type: 'bytes' },
      { name: 'noderailsSignature', type: 'bytes' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'withdrawSettlementBalance',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'merchant', type: 'address' },
      { name: 'token', type: 'address' },
      { name: 'amount', type: 'uint256' },
      { name: 'destination', type: 'address' },
      { name: 'withdrawId', type: 'bytes32' },
      { name: 'authValidUntil', type: 'uint256' },
      { name: 'merchantSignature', type: 'bytes' },
      { name: 'noderailsSignature', type: 'bytes' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'bankSettlementConsumed',
    stateMutability: 'view',
    inputs: [{ name: 'bankSettlementId', type: 'bytes32' }],
    outputs: [{ name: '', type: 'bool' }],
  },
  {
    type: 'function',
    name: 'withdrawSettlementConsumed',
    stateMutability: 'view',
    inputs: [{ name: 'withdrawId', type: 'bytes32' }],
    outputs: [{ name: '', type: 'bool' }],
  },
  {
    type: 'function',
    name: 'merchantSettlementBalances',
    stateMutability: 'view',
    inputs: [
      { name: 'merchant', type: 'address' },
      { name: 'token', type: 'address' },
    ],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'allowedSwapRouters',
    stateMutability: 'view',
    inputs: [{ name: 'router', type: 'address' }],
    outputs: [{ name: '', type: 'bool' }],
  },
  {
    type: 'function',
    name: 'allowedBridgeRouters',
    stateMutability: 'view',
    inputs: [{ name: 'router', type: 'address' }],
    outputs: [{ name: '', type: 'bool' }],
  },
  {
    type: 'function',
    name: 'allowedSettlementTokens',
    stateMutability: 'view',
    inputs: [{ name: 'token', type: 'address' }],
    outputs: [{ name: '', type: 'bool' }],
  },
  {
    type: 'function',
    name: 'settlementCreditConsumed',
    stateMutability: 'view',
    inputs: [{ name: 'paymentIntentId', type: 'bytes32' }],
    outputs: [{ name: '', type: 'bool' }],
  },
  {
    type: 'function',
    name: 'settleBridgeRetryCount',
    stateMutability: 'view',
    inputs: [{ name: 'paymentIntentId', type: 'bytes32' }],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'getPayment',
    stateMutability: 'view',
    inputs: [{ name: 'paymentIntentId', type: 'bytes32' }],
    outputs: [
      {
        name: '',
        type: 'tuple',
        components: [
          { name: 'merchant', type: 'address' },
          { name: 'payer', type: 'address' },
          { name: 'token', type: 'address' },
          { name: 'amount', type: 'uint256' },
          { name: 'feeBps', type: 'uint16' },
          { name: 'status', type: 'uint8' },
          { name: 'timelocks', type: 'uint256' },
        ],
      },
    ],
  },
  {
    type: 'function',
    name: 'feeRecipient',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'address' }],
  },
  {
    type: 'function',
    name: 'MAX_SETTLE_BRIDGE_RETRIES',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'SETTLE_BRIDGE_RETRY_DELAY',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'settleBridgeLastAttemptAt',
    stateMutability: 'view',
    inputs: [{ name: 'paymentIntentId', type: 'bytes32' }],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'feeOnTransferEnabled',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'bool' }],
  },
  {
    type: 'function',
    name: 'fullStopped',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'bool' }],
  },
  {
    type: 'function',
    name: 'getKeyRole',
    stateMutability: 'view',
    inputs: [{ name: 'key', type: 'address' }],
    outputs: [{ name: '', type: 'uint8' }],
  },
  {
    type: 'function',
    name: 'paused',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'bool' }],
  },
  {
    type: 'function',
    name: 'isSuperAdminSigner',
    stateMutability: 'view',
    inputs: [{ name: 'account', type: 'address' }],
    outputs: [{ name: '', type: 'bool' }],
  },
  {
    type: 'function',
    name: 'superAdminSigner',
    stateMutability: 'view',
    inputs: [{ name: 'index', type: 'uint256' }],
    outputs: [{ name: '', type: 'address' }],
  },
  {
    type: 'function',
    name: 'emergencyWithdrawInitiatedAt',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'emergencyWithdrawTo',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'address' }],
  },
  {
    type: 'function',
    name: 'pause',
    stateMutability: 'nonpayable',
    inputs: [],
    outputs: [],
  },
  {
    type: 'function',
    name: 'unpause',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'proof', type: 'tuple', components: superAdminProofComponents }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'fullStop',
    stateMutability: 'nonpayable',
    inputs: [],
    outputs: [],
  },
  {
    type: 'function',
    name: 'liftFullStop',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'proof', type: 'tuple', components: superAdminProofComponents }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'setKeyRole',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'key', type: 'address' },
      { name: 'role', type: 'uint8' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'setKeyRole',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'key', type: 'address' },
      { name: 'role', type: 'uint8' },
      { name: 'proof', type: 'tuple', components: superAdminProofComponents },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'initiateEmergencyWithdraw',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'tokens', type: 'address[]' },
      { name: 'to', type: 'address' },
      { name: 'proof', type: 'tuple', components: superAdminProofComponents },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'executeEmergencyWithdrawAll',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'proof', type: 'tuple', components: superAdminProofComponents }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'cancelEmergencyWithdraw',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'proof', type: 'tuple', components: superAdminProofComponents }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'rotateSuperAdmin',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'index', type: 'uint8' },
      { name: 'next', type: 'address' },
      { name: 'proof', type: 'tuple', components: superAdminProofComponents },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'setSwapRouter',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'router', type: 'address' },
      { name: 'allowed', type: 'bool' },
      { name: 'proof', type: 'tuple', components: superAdminProofComponents },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'setBridgeRouter',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'router', type: 'address' },
      { name: 'allowed', type: 'bool' },
      { name: 'proof', type: 'tuple', components: superAdminProofComponents },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'setAllowedSettlementToken',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'token', type: 'address' },
      { name: 'allowed', type: 'bool' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'setFeeOnTransferEnabled',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'enabled', type: 'bool' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'setFeeRecipient',
    stateMutability: 'nonpayable',
    inputs: [
      { name: '_feeRecipient', type: 'address' },
      { name: 'proof', type: 'tuple', components: superAdminProofComponents },
    ],
    outputs: [],
  },
  // ── Events ──
  {
    type: 'event',
    name: 'PaymentCaptured',
    inputs: [
      { name: 'paymentIntentId', type: 'bytes32', indexed: true },
      { name: 'merchant', type: 'address', indexed: true },
      { name: 'payer', type: 'address', indexed: true },
      { name: 'token', type: 'address', indexed: false },
      { name: 'amount', type: 'uint256', indexed: false },
      { name: 'feeBps', type: 'uint16', indexed: false },
      { name: 'timelocks', type: 'uint256', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'PaymentSettled',
    inputs: [
      { name: 'paymentIntentId', type: 'bytes32', indexed: true },
      { name: 'merchant', type: 'address', indexed: true },
      { name: 'merchantAmount', type: 'uint256', indexed: false },
      { name: 'platformFee', type: 'uint256', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'DisputeInitiated',
    inputs: [
      { name: 'paymentIntentId', type: 'bytes32', indexed: true },
      { name: 'merchant', type: 'address', indexed: true },
      { name: 'payer', type: 'address', indexed: true },
    ],
  },
  {
    type: 'event',
    name: 'DisputeResolved',
    inputs: [
      { name: 'paymentIntentId', type: 'bytes32', indexed: true },
      { name: 'winner', type: 'address', indexed: false },
      { name: 'amount', type: 'uint256', indexed: false },
      { name: 'platformFee', type: 'uint256', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'PaymentRefunded',
    inputs: [
      { name: 'paymentIntentId', type: 'bytes32', indexed: true },
      { name: 'payer', type: 'address', indexed: true },
      { name: 'amount', type: 'uint256', indexed: false },
      { name: 'remainingSettleAmount', type: 'uint256', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'MerchantBalanceCredited',
    inputs: [
      { name: 'paymentIntentId', type: 'bytes32', indexed: true },
      { name: 'merchant', type: 'address', indexed: true },
      { name: 'token', type: 'address', indexed: false },
      { name: 'amount', type: 'uint256', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'SettledToMerchantBalance',
    inputs: [
      { name: 'paymentIntentId', type: 'bytes32', indexed: true },
      { name: 'merchant', type: 'address', indexed: true },
      { name: 'merchantAmount', type: 'uint256', indexed: false },
      { name: 'platformFee', type: 'uint256', indexed: false },
      { name: 'bridged', type: 'bool', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'SettledToBank',
    inputs: [
      { name: 'paymentIntentId', type: 'bytes32', indexed: true },
      { name: 'bankSettlementId', type: 'bytes32', indexed: true },
      { name: 'merchant', type: 'address', indexed: true },
      { name: 'depositAddress', type: 'address', indexed: false },
      { name: 'token', type: 'address', indexed: false },
      { name: 'amount', type: 'uint256', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'SettlementBalanceWithdrawn',
    inputs: [
      { name: 'withdrawId', type: 'bytes32', indexed: true },
      { name: 'merchant', type: 'address', indexed: true },
      { name: 'destination', type: 'address', indexed: true },
      { name: 'token', type: 'address', indexed: false },
      { name: 'amount', type: 'uint256', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'SettlementBridgeRetried',
    inputs: [
      { name: 'paymentIntentId', type: 'bytes32', indexed: true },
      { name: 'merchant', type: 'address', indexed: true },
      { name: 'amount', type: 'uint256', indexed: false },
      { name: 'retryCount', type: 'uint256', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'StuckMerchantBalanceSettled',
    inputs: [
      { name: 'paymentIntentId', type: 'bytes32', indexed: true },
      { name: 'merchant', type: 'address', indexed: true },
      { name: 'token', type: 'address', indexed: false },
      { name: 'promised', type: 'uint256', indexed: false },
      { name: 'destination', type: 'address', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'FeeOnTransferEnabledUpdated',
    inputs: [{ name: 'enabled', type: 'bool', indexed: false }],
  },
] as const;

const merchantManagerPermitComponents = [
  { name: 'amount', type: 'uint256' },
  { name: 'deadline', type: 'uint256' },
  { name: 'v', type: 'uint8' },
  { name: 'r', type: 'bytes32' },
  { name: 's', type: 'bytes32' },
] as const;

export const merchantManagerAbi = [
  {
    type: 'function',
    name: 'executePayout',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'payoutIntentId', type: 'bytes32' },
      { name: 'merchantWallet', type: 'address' },
      { name: 'recipient', type: 'address' },
      { name: 'token', type: 'address' },
      { name: 'amount', type: 'uint256' },
      { name: 'feeBps', type: 'uint16' },
      { name: 'sessionExpiry', type: 'uint256' },
      { name: 'permitData', type: 'tuple', components: merchantManagerPermitComponents },
      { name: 'merchantSignature', type: 'bytes' },
      { name: 'noderailsSignature', type: 'bytes' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'executeNativePayout',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'payoutIntentId', type: 'bytes32' },
      { name: 'merchantWallet', type: 'address' },
      { name: 'recipient', type: 'address' },
      { name: 'amount', type: 'uint256' },
      { name: 'feeBps', type: 'uint16' },
      { name: 'sessionExpiry', type: 'uint256' },
      { name: 'merchantSignature', type: 'bytes' },
      { name: 'noderailsSignature', type: 'bytes' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'executeBulkPayout',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'payoutIntentId', type: 'bytes32' },
      { name: 'merchantWallet', type: 'address' },
      { name: 'token', type: 'address' },
      { name: 'recipients', type: 'address[]' },
      { name: 'amounts', type: 'uint256[]' },
      { name: 'feeBps', type: 'uint16' },
      { name: 'sessionExpiry', type: 'uint256' },
      { name: 'permitData', type: 'tuple', components: merchantManagerPermitComponents },
      { name: 'merchantSignature', type: 'bytes' },
      { name: 'noderailsSignature', type: 'bytes' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'executeBulkNativePayout',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'payoutIntentId', type: 'bytes32' },
      { name: 'merchantWallet', type: 'address' },
      { name: 'recipients', type: 'address[]' },
      { name: 'amounts', type: 'uint256[]' },
      { name: 'feeBps', type: 'uint16' },
      { name: 'sessionExpiry', type: 'uint256' },
      { name: 'merchantSignature', type: 'bytes' },
      { name: 'noderailsSignature', type: 'bytes' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'depositETH',
    stateMutability: 'payable',
    inputs: [{ name: 'merchantWallet', type: 'address' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'withdrawETH',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'merchantWallet', type: 'address' },
      { name: 'amount', type: 'uint256' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'merchantETHBalance',
    stateMutability: 'view',
    inputs: [{ name: 'merchantWallet', type: 'address' }],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'isPayoutExecuted',
    stateMutability: 'view',
    inputs: [{ name: 'payoutIntentId', type: 'bytes32' }],
    outputs: [{ name: '', type: 'bool' }],
  },
  {
    type: 'function',
    name: 'getPayoutRecord',
    stateMutability: 'view',
    inputs: [{ name: 'payoutIntentId', type: 'bytes32' }],
    outputs: [
      {
        name: '',
        type: 'tuple',
        components: [
          { name: 'executed', type: 'bool' },
          { name: 'merchantWallet', type: 'address' },
          { name: 'totalAmount', type: 'uint256' },
          { name: 'executedAt', type: 'uint256' },
        ],
      },
    ],
  },
  {
    type: 'function',
    name: 'isSuperAdminSigner',
    stateMutability: 'view',
    inputs: [{ name: 'account', type: 'address' }],
    outputs: [{ name: '', type: 'bool' }],
  },
  {
    type: 'function',
    name: 'superAdminSigner',
    stateMutability: 'view',
    inputs: [{ name: 'index', type: 'uint256' }],
    outputs: [{ name: '', type: 'address' }],
  },
  {
    type: 'function',
    name: 'getKeyRole',
    stateMutability: 'view',
    inputs: [{ name: 'key', type: 'address' }],
    outputs: [{ name: '', type: 'uint8' }],
  },
  {
    type: 'function',
    name: 'paused',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'bool' }],
  },
  {
    type: 'function',
    name: 'fullStopped',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'bool' }],
  },
  {
    type: 'function',
    name: 'isFullStopped',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'bool' }],
  },
  {
    type: 'function',
    name: 'emergencyWithdrawInitiatedAt',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'emergencyWithdrawTo',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'address' }],
  },
  {
    type: 'function',
    name: 'pause',
    stateMutability: 'nonpayable',
    inputs: [],
    outputs: [],
  },
  {
    type: 'function',
    name: 'fullStop',
    stateMutability: 'nonpayable',
    inputs: [],
    outputs: [],
  },
  {
    type: 'function',
    name: 'setKeyRole',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'key', type: 'address' },
      { name: 'role', type: 'uint8' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'unpause',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'proof', type: 'tuple', components: superAdminProofComponents }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'liftFullStop',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'proof', type: 'tuple', components: superAdminProofComponents }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'initiateEmergencyWithdraw',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'tokens', type: 'address[]' },
      { name: 'to', type: 'address' },
      { name: 'proof', type: 'tuple', components: superAdminProofComponents },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'executeEmergencyWithdrawAll',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'proof', type: 'tuple', components: superAdminProofComponents }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'cancelEmergencyWithdraw',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'proof', type: 'tuple', components: superAdminProofComponents }],
    outputs: [],
  },
  // ── Events ──
  {
    type: 'event',
    name: 'PayoutExecuted',
    inputs: [
      { name: 'payoutIntentId', type: 'bytes32', indexed: true },
      { name: 'merchantWallet', type: 'address', indexed: true },
      { name: 'recipient', type: 'address', indexed: true },
      { name: 'token', type: 'address', indexed: false },
      { name: 'amount', type: 'uint256', indexed: false },
      { name: 'fee', type: 'uint256', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'NativePayoutExecuted',
    inputs: [
      { name: 'payoutIntentId', type: 'bytes32', indexed: true },
      { name: 'merchantWallet', type: 'address', indexed: true },
      { name: 'recipient', type: 'address', indexed: true },
      { name: 'amount', type: 'uint256', indexed: false },
      { name: 'fee', type: 'uint256', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'BulkPayoutCompleted',
    inputs: [
      { name: 'payoutIntentId', type: 'bytes32', indexed: true },
      { name: 'merchantWallet', type: 'address', indexed: true },
      { name: 'token', type: 'address', indexed: false },
      { name: 'totalAmount', type: 'uint256', indexed: false },
      { name: 'totalFee', type: 'uint256', indexed: false },
      { name: 'count', type: 'uint256', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'BulkNativePayoutCompleted',
    inputs: [
      { name: 'payoutIntentId', type: 'bytes32', indexed: true },
      { name: 'merchantWallet', type: 'address', indexed: true },
      { name: 'totalAmount', type: 'uint256', indexed: false },
      { name: 'totalFee', type: 'uint256', indexed: false },
      { name: 'count', type: 'uint256', indexed: false },
    ],
  },
] as const;
